version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=user4
      - POSTGRES_PASSWORD=sistemas4
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=sistemas4
      - MYSQL_PORT=3306
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
